config/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls import handler404
from django.conf.urls.static import static
from django.utils.translation import gettext_lazy as _

urlpatterns = i18n_patterns(
    path(_('admin/'), admin.site.urls),
    path('', include('myprint.urls')),
    path('rosetta/', include('rosetta.urls')),

) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'myprint.views.not_found_page'

myprint/urls.py
from unicodedata import name
from django.urls import path
from .views import *

 
app_name = "myprint"

urlpatterns = [
    path('', home, name='home'),
    path('logout/', logoutview, name='logout'),
    path('parent/<int:pk>/', parent, name='parent'),
    path('parent_product/<int:pk>/', parent_product, name='parent_product'),
    path('contact/', contact, name='contact'),
    path('portfolio/', portfolio, name='portfolio'),
    path('design/', design, name='design'),
    path('printing_large/', printing_large, name='printing_large'),
    path('promotional_products/', promotional_products, name='promotional_products'),
    path('markirovka/', markirovka, name='markirovka'),
    path('printing_paper/', printing_paper,  name='printing_paper'),
    path('printing_textile/', printing_textile, name='printing_textile'),
    path('textile_products/', textile_products, name='textile_products'),
    path('advertisement/', aboutview, name='advertisement'),
    path('all/', Home.as_view(), name='all'),
    path('create/', createView, name="create"),
    path('list/', listView, name="list"),
    path('user_login_view/', user_login, name='login'),
    path('create-pdf/', generate_pdf, name="create_pdf"),
    path('aboutview/', aboutview, name='aboutview'),
    path('servicecategory/', servicecategory, name='servicecategory'),
]

templates/main/about.html
{% extends 'base.html' %}

{% load static %}
{% load i18n %}

{% block content %}


    <section class="container-fluid">
        <div class="container pt-5 pb-5">
            <div class="row">
                <div class="col-12"><h6><span><a href="{% url 'myprint:home' %}"
                                                 class="text-decoration-none colorBlack"><i class="fa fa-home"></i>{% trans " Главная" %}</a></span>
                    / <a href="#!" class="colorBlack">{% trans " Услуга " %}</a> / <span>{% trans "Наружная реклама" %}</span></h6></div>
                <div class="col-12 pt-3">
                    <h1 class="font-weight-bold h2 text-center pb-3">{% trans "Наружная реклама" %}</h1>
                    {% for des in about %}
                        <h6 class="font-weight-normal text-justify">{{ des.description }}</h6>
                    {% endfor %}
                </div>
            </div>
            <div class="row">
                {% for img in image %}
                    <div class="col-12 col-sm-6 col-md-6 col-lg-4 col-xl-3 p-2">
                        <div class="text-right"
                             style="background-image: url('{{ img.image.url }}'); background-size: cover; height: 200px;">
                            <div class="p-3" style="background-color: rgba(0,0,0,0.5); height:100%;">
                                <h5 class="pb-5 pt-2 text-white text-left">{{ img.name }}</h5>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </section>

{% endblock content %}

templates/main/contact.html
{% extends 'base.html' %}

{% load static %}
{% load i18n %}
{% block content %}
    <section class="container-fluid pt-5 pb-5">
		<div class="container">
			<div class="row">
				<div class="col-12 col-sm-12 col-md-12 col-lg-6 col-xl-6 pt-1">
					<h1 class="pl-2 pb-3 text_h2">{% trans "Шайхантахурский филиал" %}</h1>
					<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2996.458337188178!2d69.26311225108576!3d41.32064580799094!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x38ae8bae8aeca577%3A0x9b4821e45adc835a!2sMyprint.uz!5e0!3m2!1sru!2s!4v1653091185199!5m2!1sru!2s" width="100%" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
                </div>
				<div class="col-12 col-sm-12 col-md-6 col-lg-6 col-xl-6 pl-3 pr-3 pt-5">
					<img src="{% static 'img/shayxontohur-filiali.jpg' %}" width="100%" alt="">
					<div class="media pt-3 borderDashedBottom">
						<span><i class="fa fa-map-marked-alt text-secondary fa-2x"></i></span>
						<div class="media-body">
							<h6 class="pl-3 pt-2">{{location1}}</h6>
						</div>	
					</div>
					<div class="media pt-3">
						<span><i class="fa fa-phone-alt text-secondary fa-2x"></i></span>
						<div class="media-body">
							<h5   class="font-weight-bold pl-3"><a href="tel:{{ phone }}" class="pb-0 pt-3 mb-0 font-weight-normal" style="font-size: 25px;">{{ phone }}</a><h6 class="pl-4">{{work_info1}}</h6></h5>
						</div>	
					</div>
				</div>

				<div class="col-12 col-sm-12 col-md-12 col-lg-6 col-xl-6 pt-5">
					<h1 class="pl-2 pb-3 text_h2">{% trans "Учтепинский филиал" %}</h1>
					<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2997.7587596741487!2d69.19175495108492!3d41.29235450974208!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x38ae8981d0f06e99%3A0xd489b02307a8014c!2smyprint.uz!5e0!3m2!1sru!2s!4v1653091265905!5m2!1sru!2s" width="100%" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
                </div>
				<div class="col-12 col-sm-12 col-md-6 col-lg-6 col-xl-6 pl-3 pr-3 pt-5 mt-5">
					<img src="{% static 'img/uchtepa-filiali.jpg' %}" width="100%" alt="">
					<div class="media pt-3">
						<span><i class="fa fa-map-marked-alt text-secondary fa-2x"></i></span>
						<div class="media-body">
							<h6 class="pl-3 pt-2">{{location2}}</h6>
						</div>	
					</div>
					<div class="media pt-3">
						<span><i class="fa fa-phone-alt text-secondary fa-2x"></i></span>
						<div class="media-body">
							<h5 class="font-weight-bold pl-3"><a href="tel:{{ phone }}" class="pb-0 pt-3 mb-0 font-weight-normal" style="font-size: 25px;">{{ phone }}</a><h6 class="pl-4">{{work_info2}}</h6></h5>
						</div>	
					</div>
				</div>
			</div>
		</div>
	</section>

	{% endblock content %}

	
	

templates/main/error.html
{% extends 'base.html' %}

{% load i18n %}
{% block content %}
    <div class="container-fluid pb-5 pt-5">
        <div class="container pt-4 pb-5 pl-5 pr-5 ">
            <div class="row pt-2">
                <div class="col-12 col-sm-12 col-md-12 col-lg-8 col-xl-6 p-5 m-auto text-center border">
                    <h2 class="text-dark pb-5 font-weight-bold">{% trans "LOGIN SUPPORT CENTER" %}</h2>
                    <h1>{% trans "ERROR !!!!!!!!!" %}</h1>
                    <p>{% trans "Если вы еще не создали учетную запись" %}
                        <a href="{% url 'myprint:login' %}" class="text-secondary">{% trans "Try again" %}</a>
                    </p>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/main/gifts-products.html
{% extends 'base.html' %}

{% load i18n %}
{% load static %}



{% block content %}

    <section class="container-fluid pl-0 pr-0">
        
        <div class="container d-flex pb-5 pt-5">

            <div class="col-12 col-sm-12 col-md-6 col-lg-4 col-xl-3 border pl-0 pr-0">
                <div class="p-2 text-center">
                    <div class="border bgSecondary shadow-lg" style="padding: 5px 0px 1px 0px;">
                        <h5 class="font-weight-bold">{% trans "Products" %}</h5>
                    </div>
                </div>

                {% for par in product %}
                    <a class='text-dark' href="{% url 'myprint:parent_product' par.id %}">
                        <div class="pt-3 pb-1 pl-3 borderDashedBottom">
                            <h6>
                                <img 
                                    src="{{ par.image.url }}" 
                                    width="20" 
                                    alt="category-title-icon"
                                    class="mr-1"
                                >
                                {{ par.name }}
                            </h6>
                        </div>
                    </a>
                {% endfor %}
            </div>
            
            <div class="row category-list">
                
                
            
                        {% for pro in products %}
                            <div class="col-12 col-sm-6 col-md-6 col-lg-3 col-xl-4 p-2">
                                    <div class="card p-3 bg-transparent">
                                        <a href="id{{ pro.id }}" data-toggle="modal" data-target="#id{{ pro.id }}">
                                            <img src="{{ pro.image.url }}" width="100%" height="220" alt="">
                                            <h6 class="font-weight-normal small text-dark text-left p-2 borderDashedBottom"
                                                style="height: 45px; overflow: hidden;">{{ pro.name }}</h6>
                                            <h6 class="colorBlack small pl-1">{% trans "Артикул :" %} {{ pro.vendor_code }}</h6>
                                        </a>
                                        <button 
                                            class="btn btn-sm pl-4 pr-4 bgOrange" type="button"
                                            class="btn btn-secondary"
                                            data-toggle="modal" data-target="#orderModal">{% trans "Заказать" %}
                                        </button>
                                    </div>
                                    
                            </div>
                            <div class="modal fade" id="id{{ pro.id }}" tabindex="-1" role="dialog"
                                 aria-labelledby="example#{{ pro.id }}"
                                 aria-hidden="true">
                                <div class="modal-dialog modal-dialog-centered" role="document">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title pl-3" id="id{{ pro.id }}">{% trans "Календарь" %}</h5>
                                            <button type="button" class="btn btn-outline-danger btn-sm mt-1 mr-3"
                                                    data-dismiss="modal">{% trans "Закрыть" %}
                                            </button>
                                        </div>
                                        <div class="modal-body">
                                            <div class="container">
                                                <div class="row">
                                                    <div class="col-12 col-sm-4 col-md-4 col-lg-4 col-xl-3">
                                                        <img src="{{ pro.image.url }}" width="100%"
                                                             alt="">
                                                    </div>
                                                    <table>
                                                        <thead>
                                                        <tr>
                                                            <th>{% trans "Nomi" %}</th>
                                                            <th>{% trans "Masulot turi" %}</th>
                                                            <th>{% trans "Sotuvchi kodi" %}</th>
                                                        </tr>
                                                        </thead>
                                                        <tbody>
                                                        <tr>
                                                            <td>
                                                                {{ pro.name }}
                                                            </td>
                                                            <td>
                                                                {{ pro.category }}
                                                            </td>
                                                            <td>
                                                                {{ pro.vendor_code }}
                                                            </td>
                                                        </tr>
                                                        </tbody>
                                                    </table>
                                                    <!-- Scrollable modal -->
                                                    <div class="modal-dialog modal-dialog-scrollable">
                                                        {{ pro.description }}
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="modal fade" id="orderModal" tabindex="-1" role="dialog"
                                 aria-labelledby="exampleModalLabel"
                                 aria-hidden="true">
                                <div class="modal-dialog modal-dialog-centered " role="document">
                                    <div class="modal-content pl-3 pr-3">
                                        <div class="modal-header">
                                            <h5 class="modal-title" id="exampleModalLabel"></h5>
                                            <button type="button" class="btn btn-sm btn-danger" data-dismiss="modal">
                                                Yopish
                                            </button>
                                        </div>
                                        <div class="modal-body pt-2 pb-5 text-center">
                                            <h6>{% trans "Bizning menejerimiz imkon qadar tezroq siz bilan bog'lanadi!" %}</h6>
                                            <form method="POST">
                                                {% csrf_token %}
                                                {{ form.name }}
                                                {{ form.vendor_code }}
                                                {{ form.phone }}
                                                <div class="modal-footer">
                                                    <button type="submit" class="btn btn-success btn-sm">{% trans "So'rov qoldiring" %}</button>
                                                </div>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock content %}

templates/main/index.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}

{% block content %}
	 <section class="container-fluid pl-0 pr-0 overflow-hidden header-slider">
		<div class="container-fluid" style="background-color: rgba(0,0,0,0.5); width: 100%; height: 100%;">
				<div class="row">
					<div class="col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12 pt-3">
						<div class='console-container'><span id='text'></span></div>
					</div>
					</div>
				</div>
		</div>
	</section> 


<section class="container-fluid pl-0 pr-0 pt-5" id="servic_section">     
	<div class="container pt-5">
		<div class="row">
		  <ul class="nav nav-tabs" role="tablist">
			{% for service in servistype %}
                        <li class="nav-item col-12 col-sm-12 col-md-6 col-lg-4 col-xl-4">
                            <a class="text-dark" href="{% url 'myprint:portfolio' %}">
                                <div class="card bg-transparent border-0 text-center p-2">
                                    <img src="{{ service.image.url }}"  width="95%" height="220"
                                         class="m-auto">
                                    <a href="{% url 'myprint:servicecategory' %}" class="pt-3 text-dark" >{{ service.name }}</a>
                                </div>
                            </a>
                        </li>
            {% endfor %}
		</ul>
		

		<div class="tab-content">
			<div class="tab-pane" id="tabs-1" role="tabpanel">
				
			</div>
		</div>
		</div>
	</div>
</section>  


 <section class="container-fluid pl-0 pr-0" id="about-section" style="background-image: url(img/bg/indexAboutBg.png); background-size: cover;">
	<div class="container">
		<div class="row">
		  <div class="col-12 col-sm-12 col-md-6 col-lg-6 col-xl-6 text-right">
			  <img src="{% static 'img/bg/indexAboutPerson.png' %}" width="80%" alt="">
		  </div>
		  <div class="col-12 col-sm-12 col-md-6 col-lg-6 col-xl-6 pt-5 pb-2">
			<h1 class="pad_top_about" style=" color: red; font-weight: bold;">{% trans "Кто мы ?" %}</h1>
			<h5 class="text-justify">{{description}}</h5>
		  </div>
		</div>
	</div>
  </section>  
  
 

  

  <section class="container-fluid pt-5 pb-5">
	<div class="container pl-0 pr-0">
		<div class="row">
			<div class="col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12 pb-4 text-center">
				<h2 class="text-center font-weight-bold">{% trans "Как мы работаем" %}</h2>
			</div>
			<div class="col-6 col-sm-6 col-md-6 col-lg-3 col-xl-3 text-center" style="height: 200px;">
				<img src="{% static 'img/icons/w2.svg' %}" width="80" height="100" alt="">
				<h6 class="font-weight-bold pt-3">{% trans "Оставьте заявку на сайте или позвоните" %}</h6>
			</div>
			<div class="col-6 col-sm-6 col-md-6 col-lg-3 col-xl-3 text-center" style="height: 200px;">
				<img src="{% static 'img/icons/w5.svg' %}" width="80" height="100" alt="">
				<h6 class="font-weight-bold border-left pt-3">{% trans "Подберем оптимальное решение" %}</h6>
			</div>
			<div class="col-6 col-sm-6 col-md-6 col-lg-3 col-xl-3 text-center" style="height: 200px;">
				<img src="{% static 'img/icons/w4.svg' %}" width="80" height="100" alt="">
				<h6 class="font-weight-bold border-left pt-3">{% trans "Заключение договора" %}</h6>
			</div>
			<div class="col-6 col-sm-6 col-md-6 col-lg-3 col-xl-3 text-center" style="height: 200px;">
				<img src="{% static 'img/icons/images.png' %}" width="80" height="100" alt="">
				<h6 class="font-weight-bold border-left pt-3">{% trans "Вы получаете готовый продукции" %}</h6>
			</div>
		</div>
	</div>
</section>
	
<section class="container-fluid pt-5 pb-5 border-top" style="background-image: url(img/bg/full.png);">
	<div class="container">
	 <div class="row">
	   <div class="col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
		<h2 class="text-center font-weight-bold">{% trans "Mы предлагаем" %}</h2>
	   </div>  
	 </div>

	 <div class="row pb-4 pt-3">
		
		  <div class="row">
    {% for product in products %}
    <div class="gallery_product col-12 col-sm-6 col-md-6 col-lg-4 col-xl-3 border p-3 filter {{product.subcategroy.name}}"><a href="{% url 'myprint:portfolio' %}"><img src="{{product.image.url}}" width="100%" height="230" class="img-responsive"></a></div>
    {% endfor %}
</div>
</div>
</section> 



		<section class="container-fluid pl-0 pr-0" style=" background-image: url({% static 'img/bg/head.jpg'%});">
			<div class="container-fluid" style="background-color: rgba(0,0,0,.3);">
				<div class="container pb-5 pt-5">
					<div class="row">
						<div class="col-12 col-sm-12 col-md-6 col-lg-6 col-xl-6 text-white">
							<h1 class="font-weight-bold text_h1">{% trans "Есть вопросы ?" %}</h1>
							<h2>
								<img src="{% static 'img/type/phone-white.svg' %}" class="mb-2" style="color: #0fa123;" width="40" alt="">
								<span class="h2 font-weight-bold text_h1 font-weight-normal" ><a href="tel:{{ phone }}"
									class="pb-0 pt-3 mb-0 font-weight-normal"
									style="font-size: 25px;"><img src="{% static 'img/icons/phonesvg.svg' %}" width="25" class="mr-2 ml-2" height="30" alt="">{{ phone }}</a></span>
							</h2>
							</div>
						<div class="col-12 col-sm-12 col-md-6 col-lg-6 col-xl-6 text-white">
							<h1 class="font-weight-bold text_h1">{% trans "Звоните! " %}</h1>
							<h2 class="font-weight-bold text_h1">{% trans "Мы всегда рады!" %}</h2>
						</div>
					</div>
				</div>
			</div>
		</section>
		
	
		<section class="container-fluid pt-5 pb-5">
			<div class="container pl-0 pr-0">
				<div class="row">
					<div class="col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12 pb-2 text-center">
						<h2><span class="h2 font-weight-bold">{% trans "Наши преимущества" %}</span></h2>
					</div>
					<div class="col-12 col-sm-12 col-md-6 col-lg-3 col-xl-4 text-center p-3">
						<div class="media">
							<img src="{% static 'img/icons/icoP1.svg' %}" width="60" height="100" alt="">
							<div class="media-body pl-3 text-left">
								<h6 class="font-weight-bold  pt-3">{% trans "Заказ любого объема" %}</h6>
								<small>{% trans "Типография полного цикла предполагает изготовление заказа любого объема и сложности." %}</small>
							</div>
						</div>
					</div>
					<div class="col-12 col-sm-12 col-md-6 col-lg-3 col-xl-4 text-center p-3">
						<div class="media">
							<img src="{% static 'img/icons/w4.svg' %}" width="60" height="100" alt="">
							<div class="media-body pl-3 text-left">
								<h6 class="font-weight-bold pt-3">{% trans "Доступные цены" %}</h6>
								<small>{% trans "Мы гарантируем высочайшее качество печати по доступным ценам." %}</small>
							</div>
						</div>
					</div>
					<div class="col-12 col-sm-12 col-md-6 col-lg-3 col-xl-4 text-center p-3">
						<div class="media">
							<img src="{% static 'img/icons/images.png' %}" width="60" height="100" alt="">
							<div class="media-body pl-3 text-left">
								<h6 class="font-weight-bold pt-3">{% trans "Соблюдение сроков сдачи" %}</h6>
								<small>{% trans "Отлаженные процессы выполнения заказов гарантируют соблюдение оптимальных сроков." %}</small>
							</div>
						</div>
						
					</div>
					<div class="col-12 col-sm-12 col-md-6 col-lg-3 col-xl-4 text-center p-3">
						<div class="media">
							<img src="{% static 'img/icons/images.png' %}" width="60" height="100" alt="">
							<div class="media-body pl-3 text-left">
								<h6 class="font-weight-bold pt-3">{% trans "Различные виды печати" %}</h6>
								<small>{% trans "Представляем цифровую печать, офсетную печать, широкоформатную печать и т.д." %}</small>
							</div>
						</div>					
					</div>
					<div class="col-12 col-sm-12 col-md-6 col-lg-3 col-xl-4 text-center p-3">
						<div class="media">
							<img src="{% static 'img/icons/w5.svg' %}" width="60" height="100" alt="">
							<div class="media-body pl-3 text-left">
						<h6 class="font-weight-bold pt-3">{% trans "Контроль качества" %}</h6>
								<small>{% trans "На каждом этапе производства продукции специалисты тщательно следят за ее качеством." %}</small>
							</div>
						</div>
					</div>
					<div class="col-12 col-sm-12 col-md-6 col-lg-3 col-xl-4 text-center p-3">
						<div class="media">
							<img src="{% static 'img/icons/icoP6.svg' %}" width="60" height="100" alt="">
							<div class="media-body pl-3 text-left">
						<h6 class="font-weight-bold pt-3">{% trans "Собственная дизайн-студия" %}</h6>
								<small>{% trans "Наши дизайнеры настоящие профессионалы, воплощающие Ваше видение в чудесные макеты." %}</small>
							</div>
						</div>
					</div>
				</div>
			</div>
		</section>

		<div class="bg-video-wrap">
			<video src="{% static 'img/video/videoplayback.mp4' %}" loop muted autoplay></video>
			<div class="overlay"></div>
			<h1 style="font-size: 3em;" class="text-uppercase">{% trans "наша цель - Быть партнерами лучших, <br> быть лучшими партнерами" %}</h1> 
		  </div>



	<section class="container-fluid pt-5 pb-5 border-top">
		<div class="container pl-0 pr-0">
			<div class="row">
				<div class="col-12 pb-2">
					<h2 class="text-center font-weight-bold">{% trans "Нам доверяют" %}</h2>
				</div>
				{% for i in sponsor %}
				<div class="col-6 col-sm-4 col-md-3 col-lg-2 col-xl-1 p-1"><div class="p-0 text-center"><img width="100%" src='{{i.image.url}}' alt="clients-logo"></div></div>
				{% endfor %}
			</div>
		</div>
	</section>
	<section class="container-fluid pl-0 pr-0" style="background-image: url(); background-size: cover;">
		<div class="container pl-0 pr-0 pt-5 ">
			<div class="row">
			  <div class="col-12 col-sm-12 col-md-6 col-lg-6 col-xl-6 p-5">
				<div class="card bg-transparent border-0 pt-3">
				  <form action="" method="POST">
					
					<h1 class="" style="padding-top: 130px; color: red; font-weight: normal;">{% trans "Остались Вопросы? " %}</h1>
					<h5 class="pt-3 pb-3">{% trans "Оставляйте свой номер телефона и мы перезвоним Вам в течение 50 секунд!" %}</h5>
						{% csrf_token %}
					{{ form.username }}
					{{ form.phone_number }}
					<button type="submit" class="btn btn-success pl-3 pr-3 mt-3 ">{% trans "ЖДУ ЗВОНОК!" %}</button>
				</form>
			</div>
			  </div>
			  <div class="col-12 col-sm-12 col-md-6 col-lg-6 col-xl-6 text-right pb-0">
				<img src="{% static 'img/bg/indexAboutPerson.png' %}" width="80%" alt="">
			</div>
			</div>
		</div>
	  </section>

{% endblock content %}

templates/main/login.html
{% extends 'base.html' %}

{% load i18n %}
{% block content %}
    <div class="container-fluid pb-5 pt-5">
        <div class="container pt-4 pb-5 pl-5 pr-5 ">
            <div class="row pt-2">
                <div class="col-12 col-sm-12 col-md-12 col-lg-8 col-xl-6 p-5 m-auto text-center border">
                    <h2 class="text-dark pb-5 font-weight-bold">{% trans "Авторизоваться" %}</h2>
                    <form class="" method="POST" action="">
                        {% csrf_token %}
                        {{form.phone_number}}
                        {{form.password}}
                        <button class="btn bgRed w-100 mb-3 text-dark font-weight-bold" type="submit">{% trans "Войти" %}</button>
                    </form>
                    
                    <p><a href="{% url 'myprint:portfolio' %}" class="h6 text-dark">{% trans "Company products" %}</a></p><br>
                    <p>
                        <a href="{% url 'myprint:home' %}" class="text-secondary">{% trans "зарегистрируйтесь." %}</a>
                    </p>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/main/not_found.html
<h1>Not Found</h1>
<p>EEEEEEERRRRRRRROOOOOOOORORORRRRRRRRR</p>

templates/main/success.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}
    <div class="container-fluid pb-5 pt-5">
        <div class="container pt-4 pb-5 pl-5 pr-5 ">
            <div class="row pt-2">
                <div class="col-12 col-sm-12 col-md-12 col-lg-8 col-xl-6 p-5 m-auto text-center border">
                    <h2 class="text-dark pb-5 font-weight-bold">{% trans "Авторизоваться" %}</h2>
                    <h1>{% trans "Successfuly !!!!!!" %}</h1>
                    <p><a href="{% url 'myprint:create' %}" class="h6 text-dark">{% trans "START WORK" %}</a></p><br>
                </div>
            </div>
        </div>
    </div>
{% endblock %}