config/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls import handler404
from django.conf.urls.static import static
from django.utils.translation import gettext_lazy as _

urlpatterns = i18n_patterns(
    path(_('admin/'), admin.site.urls),
    path('', include('myprint.urls')),
    path('rosetta/', include('rosetta.urls')),

) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'myprint.views.not_found_page'

myprint/urls.py
from unicodedata import name
from django.urls import path
from .views import *

 
app_name = "myprint"

urlpatterns = [
    path('', home, name='home'),
    path('logout/', logoutview, name='logout'),
    path('parent/<int:pk>/', parent, name='parent'),
    path('parent_product/<int:pk>/', parent_product, name='parent_product'),
    path('contact/', contact, name='contact'),
    path('portfolio/', portfolio, name='portfolio'),
    path('design/', design, name='design'),
    path('printing_large/', printing_large, name='printing_large'),
    path('promotional_products/', promotional_products, name='promotional_products'),
    path('markirovka/', markirovka, name='markirovka'),
    path('printing_paper/', printing_paper,  name='printing_paper'),
    path('printing_textile/', printing_textile, name='printing_textile'),
    path('textile_products/', textile_products, name='textile_products'),
    path('advertisement/', aboutview, name='advertisement'),
    path('all/', Home.as_view(), name='all'),
    path('create/', createView, name="create"),
    path('list/', listView, name="list"),
    path('user_login_view/', user_login, name='login'),
    path('create-pdf/', generate_pdf, name="create_pdf"),
    path('aboutview/', aboutview, name='aboutview'),
    path('servicecategory/', servicecategory, name='servicecategory'),
]

myprint/forms.py
from dataclasses import fields
from pyexpat import model
from django import forms
from django.forms import ModelForm

from .models import *

# class OrForm(forms.ModelForm):
#     class Meta:
#         model = Form
#         fields = [
# 			'full_name',
# 			'phone_number',
# 		]


class OrderServiceForm(forms.ModelForm):
    class Meta:
        model = OrderService
        exclude = ['creat_add']

        widgets = {
            'files': forms.FileInput(attrs={
                "accept": ".xlsx,.xls,image/*,.doc,audio/*,.docx,video/*,.ppt,.pptx,.txt,.pdf",
                "type": "file",
                "class": "form-control mt-4 bg-secondary",
            }),

            'order_type': forms.Select(attrs={
                'class': 'custom-select',

            }),
            'username': forms.TextInput(attrs={
                'class': 'form-control mt-4',
                'placeholder': 'Имя...'
            }),
            'phone_number': forms.NumberInput(attrs={
                'class': 'form-control mt-3',
                'maxlength': '13',
                'placeholder': 'Телефон...',
                'value': '+998'
            })
        }


class CustomerForm(forms.ModelForm):
    id_name_order = forms.CharField(required=True)
    client = forms.CharField(required=True)
    client_phone_number = forms.CharField(required=True)
    manager_name = forms.CharField(required=True)
    date_order = forms.CharField(required=True)
    ready_product_date_order = forms.CharField(required=True)

    class Meta:
        model = Customer
        
        fields = [
			'id_name_order',
			'client',
			'client_phone_number',
            'manager_name',
            'date_order',
            'ready_product_date_order',
		]

class OrdersForm(forms.ModelForm):
	class Meta:
		model = OrderForm

		fields = [
			'name',
			'status_order',
            'amount',
            'price',
            'price_free_VAT',
            'VAT',
            'price_with_VAT',
            'total',
		]

		widgets = {
			'name': forms.TextInput(attrs={'class': 'formset-field'}),
			'status_order': forms.TextInput(attrs={'class': 'formset-field'}),
			'price': forms.NumberInput(attrs={'class': 'formset-field'}),
            'price_free_VAT': forms.NumberInput(attrs={'class': 'formset-field'}),
            'VAT': forms.NumberInput(attrs={'class': 'formset-field'}),
            'price_with_VAT': forms.NumberInput(attrs={'class': 'formset-field'}),
            'total': forms.NumberInput(attrs={'class': 'formset-field'}),
		}

class UserLoginForm(forms.Form):
    phone_number = forms.IntegerField(widget=forms.TextInput(attrs={
        "class": 'form-control mb-2 form-control',
        'type': 'number',
        'placeholder': 'Телефон ...'
    }))
    password = forms.CharField(max_length=20,widget=forms.TextInput(attrs={
        "class": 'form-control mb-5',
        'type': 'pasword',
        'placeholder': 'Пароль ...'
    }))
    class Meta:
        model = User
        widgets = {
            'password': forms.PasswordInput(),
        }


class Product_OrdersForm(forms.ModelForm):
    class Meta:
        model = Product_Orders
        exclude = ['creat_add']

        widgets = {
            'name': forms.TextInput(attrs={
                'class': 'form-control mt-4',
                'placeholder': 'Nomi...'
            }),
            'vendor_code': forms.TextInput(attrs={
                'class': 'form-control mt-3',
                'maxlength': '13',
                'placeholder': 'Maxsulod kodi...',
            }),
            'phone': forms.NumberInput(attrs={
                'class': 'form-control mt-3',
                'maxlength': '13',
                'placeholder': 'Телефон...',
                'value': '+998'
            })
        }

myprint/views.py
from cgitb import html
from django.shortcuts import render, redirect
from django.views.generic import (TemplateView, ListView, CreateView, DetailView, FormView)
from django.contrib import messages
from django.urls import reverse
from django.http import HttpResponseRedirect, HttpResponse, FileResponse
from .models import *
from .forms import *
from django.contrib.auth.decorators import login_required
from django.db import transaction, IntegrityError
from django.contrib.auth import  authenticate, logout
from multiprocessing import context
from unicodedata import name
from django.views.generic.detail import SingleObjectMixin
from .models import *
from .forms import *
from django.template.loader import get_template
from xhtml2pdf import pisa
from django.views.generic import TemplateView, CreateView
from django.forms import modelformset_factory
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth import login as auth_login
from .help_views import handle_upload_file




def home(request):
    # categories = Category.objects.filter(parent=None)
    products = Product.objects.all()
    servistype = TypeService.objects.all()
    menuservice = MenuService.objects.all()
    sponsor = Sponsors.objects.all()
    # menutarif = MenuTariff.objects.all()
    # tarif = Tariff.objects.all()
    form = OrderServiceForm()
    if request.method == 'POST':
        form = OrderServiceForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/')
    context = {
        'form': form,
        "servistype": servistype,
        "menuservice": menuservice,
        'sponsor': sponsor,
        'products' : products
    }
    return render(request, 'main/index.html', context=context)
    

def contact(request):
    return render(request, 'main/contact.html') 

def portfolio(request):
    image = Portfolio.objects.all()
    product = Product.objects.all()
    context = {
        "image": image,
        'product': product
    }
    return render(request, 'main/portfolio.html', context=context)

def gift_product(request):
    return render(request, 'main/gifts-products.html')

def design(request):
    desig = Design.objects.filter()
    image = Image2.objects.filter()
    context = {
        'desig': desig,
        'image': image
    }
    return render(request, 'main/dizayn.html', context=context)

# def service_type(request, pk):
#     service = Type_Services.objects.filter(type_id=pk)
#     image = Image.objects.filter(type_sevice_id=pk)
#     context = {
#         'service': service,
#         'pk': pk,
#         'image': image
#     }
#     return render(request, 'main/service_type.html', context=context)

@csrf_exempt
def printing_large(request):
    sub = SubLargeFormat.objects.all()
    lar = LargeFormat.objects.all()
    form = OrderServiceForm()
    if request.method == 'POST':
        form = OrderServiceForm(request.POST, request.FILES)
        print("<-----------------------__>>>>", request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Saqlandi")
            return redirect('myprint:printing_large')
        else:
            form = OrderServiceForm()
    context = {
        'form' : form,
        'sub': sub,
        'lar': lar,
    }
    return render(request, 'main/printing-largeformat.html' , context=context)

def promotional_products(request):
    return render(request, 'main/promotional-products.html')
@csrf_exempt
def markirovka(request):
    laser = LaserPrint.objects.all()
    sub = SubLaserPrint.objects.all()
    image = Image2.objects.filter()
    form = OrderServiceForm()
    if request.method == 'POST':
        form = OrderServiceForm(request.POST, request.FILES)
        if form.is_valid():
            print("<<<<<<<<<<<<<<<<<<<", request.FILES)
            form.save()
            messages.success(request, "Saqlandi")
            return redirect('myprint:markirovka')
        else:
            form = OrderServiceForm()
    context = {
        'form' : form,
        'laser': laser,
        'image': image,
        'sub': sub
    }
    return render(request, 'main/markirovka.html', context=context)


def parent(request, pk):
    products = Product.objects.filter(category_id=pk)
    subcategory = SubCategory.objects.filter(category_id=pk)
    form = Product_OrdersForm()
    if request.method == 'POST':
        form = Product_OrdersForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/')
    context = {
        'subcategory': subcategory,
        'products': products,
        'form': form,
    }
    return render(request, 'main/poligraphy-products.html', context=context)


def parent_product(request, pk):
    product = SubCategory.objects.all()
    products = Product.objects.filter(subcategory_id=pk)
    subcategory = SubCategory.objects.filter(category_id=pk)
    form = Product_OrdersForm()
    if request.method == 'POST':
        form = Product_OrdersForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/')
    context = {
        'subcategory': subcategory,
        'products': products,
        'product': product,
        'form': form,
    }
    return render(request, 'main/gifts-products.html', context=context)




@csrf_exempt
def printing_paper(request):
    dgprint = DigitalPrint.objects.all()
    sub = SubDigitalPrint.objects.all()
    image = Image2.objects.filter()
    form = OrderServiceForm()
    if request.method == 'POST':
        form = OrderServiceForm(request.POST, request.FILES)
        print("<-----------------------__>>>>", request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Saqlandi")
            return redirect('myprint:printing_paper')
        else:
            form = OrderServiceForm()
    context = {
        'form' : form,
        'dgprint': dgprint,
        'image': image,
        'sub': sub,
    }
    return render(request, 'main/printing-paper.html' , context=context)


@csrf_exempt
def printing_textile(request):
    text = TextPrint.objects.all()
    subb = SUbTextPrint.objects.all()
    image = Image2.objects.filter()
    form = OrderServiceForm()
    if request.method == 'POST':
        form = OrderServiceForm(request.POST, request.FILES)
        print("<-----------------------__>>>>", request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Saqlandi")
            return redirect('myprint:printing_textile')
        else:
            form = OrderServiceForm()
    context = {
        'form' : form,
        'image': image,
        'text' : text,
        'subb': subb,
    }
    return render(request, 'main/printing-textile.html', context=context)

def textile_products(request):
    return render(request, 'main/textile-products.html')

def advertisement(request):
    return render(request, 'main/about.html')

def invoice(request):
    return render(request, 'main/invoice.html')

def aboutview(request):
    about = About.objects.all()
    image = AboutImage.objects.all()
    context = {
        "about": about,
        "image": image
    }
    return render(request, 'main/about.html', context=context)


def servicecategory(request):
    page_service = MenuService.objects.all()
    context = {
        "page_service": page_service
    }
    return render(request, 'main/service_page.html', context=context)





@csrf_exempt
def createView(request):
    context = {}
    OrdersFormset = modelformset_factory(OrderForm, form=OrdersForm)
    form = CustomerForm(request.POST or None)
    
    formset = OrdersFormset(request.POST or None, queryset=OrderForm.objects.none(), prefix='orders')
    
    if request.method == "POST":
        if form.is_valid() and formset.is_valid():
            try:
                with transaction.atomic():
                    student = form.save(commit=False)
                    student.save()

                    for order in formset:
                        data = order.save(commit=False)
                        data.student = student
                        data.save()
            except IntegrityError:
                print("Error encountered")
            
            return redirect('myprint:list')
    context['form'] = form
    context['formset'] = formset
    return render(request, 'multi_forms/create.html', context=context)






def listView(request):
    datas = OrderForm.objects.all()
    context = {'datas' : datas}
    return render(request, 'multi_forms/list.html', context=context)














class Home(TemplateView):
    template_name = 'all.html'


@csrf_exempt
def user_login(request):
    if request.method == 'GET':
        print("GET ---------------> ")
        form = UserLoginForm()
        context={'form': form}
        print(context)
        return render(request, template_name='main/login.html', context=context)
    else:
        form = UserLoginForm(request.POST)
        
        if form.is_valid():
            
            user_name = request.POST['phone_number']
            password = request.POST['password']

            print("phone   ", user_name)
            print("password --> ", password)
            user = User.objects.filter(phone_number=user_name).first()

            user = authenticate(phone_number=user_name, password=password)
            print("user --- ", user)
            if user:    
                auth_login(request, user)
                print("login ---> ", auth_login)
                return  render(request, 'main/success.html')
            else:
                return render(request, template_name='main/error.html', context={'login': auth_login})




def not_found_page(request, exception):
    return render(request, 'main.not_found.html')

from django.http import HttpResponse
from django.shortcuts import render

from .utils import *

def generate_pdf(request):
    datas = OrderForm.objects.all()
    context = {'datas': datas}

myprint/templates/multi_forms/create.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% block content %}
<form method="POST">
    {% csrf_token %}


    <table class="table form-table table-bordered table-sm">
        <thead class="text-center">
            <tr>
                <th class="font-weight-bold">{% trans "ID" %}</th>
                <th class="font-weight-bold">{% trans " Имя ЗАКАЗЧИКА" %}</th>
                <th class="font-weight-bold">{% trans " Номер  ТЕЛЕФОНА" %}</th>
                <th class="font-weight-bold">{% trans " ОТВЕТСВЕННЫЙ  Менеджер" %}</th>
                <th class="font-weight-bold">{% trans " ДАТА ПРИЕМА ЗАКАЗА" %}</th>
                <th class="font-weight-bold">{% trans " ДАТА ОТГРУЗКИ ЗАКАЗА" %}</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>
                    <input name="id_name_order" type="text" class="form-control" placeholder="ID-№" aria-label="ID-№">
                </td>
                <td>
                    <input name="client" type="text" class="form-control" placeholder="client" aria-label="client">
                </td>
                <td>
                    <input name="client_phone_number" type="text" class="form-control" placeholder="client_phone_number"
                        aria-label="ID-№">
                </td>
                <td>
                    <input name="manager_name" type="text" class="form-control" placeholder="manager_name" aria-label="manager_name">
                </td>
                <td>
                    <input name="date_order" type="date" class="form-control" placeholder="date_order" aria-label="date_order">
                </td>
                <td>
                    <input name="ready_product_date_order" type="date" class="form-control"
                        placeholder="ДАТА ОТГРУЗКИ ЗАКАЗА" aria-label="ДАТА ОТГРУЗКИ ЗАКАЗА">
                </td>
            </tr>

        </tbody>
    </table>
    <table class="table form-table table-bordered table-sm">
        <thead class="text-center">
            <tr>
                <th class="font-weight-bold" style="width: 23%">{% trans " Nomi" %}</th>
                <th class="font-weight-bold" style="width: 23%" >{% trans "Soni" %}</th>
                <th class="font-weight-bold" style="width: 23%" >{% trans "Narxi" %}</th>
                <th class="font-weight-bold" style="width: 23%" >{% trans "Foizi" %}</th>
            </tr>
        </thead>
        <tbody>
            {{ formset.management_form }}
            {% for form_data in formset %}
                <tr class="item">
                    <td> {{ form_data.name }}   </td>
                    <td> {{ form_data.amount }} </td>
                    <td> {{ form_data.price }}  </td>
                    <td> {{ form_data.VAT }}    </td>
                    <td>
                        <button type="button" class="btn btn-danger btn-sm remove-form-row"
                                id="{{ formset.prefix }}">

                            Delete
                        </button>
                    </td>
                </tr>
            {% endfor %}
            <tr>
                <td colspan="9"
                    style="border-left: none!important; border-right: none !important; border-bottom: none!important;">
                    <button type="button" class="btn btn-sm btn-success add-form-row"
                            id="{{ formset.prefix }}">
                        Add
                    </button>
                </td>
            </tr>
            </tbody>
    </table>
    {{ formset.management_form }}

    <button 
        type="submit" 
            style="

                width: 200px; 
                height: 50px; 
                background: green; 
                color: white; 
                border: none;
                border-radius: 8px;
                margin-left: 80%;  
                margin-bottom: 20px;

            ">{% trans "Submit" %}</button>
</form>
{% endblock %}
{% block extra_script %}
<script type="text/javascript" src="{% static 'js/formset.js' %}"></script>
{% endblock%}

myprint/templates/multi_forms/list.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% block content %}
<meta charset="UTF-8">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>HTML to PDF</title>
    <style>
        @font-face {
        font-family: "Alice-Regular";
        src: url(" {% static 'Alice-Regular.ttf' %}") format("truetype");
        }

        body {
        font-family: "Alice-Regular";
        font-size: 20px
        }
        table {
            border-collapse: collapse;
            border: 1px solid black;
        }

        table td, th {
            border: 1px solid black;
        }

        td, th {
            height: 50px;
        }

        #cssTable th, td {
            text-align: center;
            vertical-align: middle;
        }
    </style>
<section class="container-fluid pt-5 pb-5">
    <div class="container p-5">
        <div class="row border p-3">
            <div class="col-12 col-sm-12 col-md-12 col-lg-6 col-xl-8">
                <h5 class="font-weight-bold">OOO «MY PRINT»</h5>
                <h6>Адрес: г.Ташкент Учтепинский р-н, 14-квартал дом № 4. Тел: 90-109-15-00</h6s>
                    <p class="pt-3 h6 ">Со склада: Участок оперативной печати склад</p>
            </div>
            <div class="col-12 col-sm-12 col-md-12 col-lg-6 col-xl-3 p-3">
                <img src="img/logo.png" width="100%" alt="">
            </div>
            <div class="col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12 ">
                <h5 class="text-center font-weight-bold pt-3">№ 0000000003 от <span
                        class="h5 font-weight-bold">02.12.2022</span></h5>
            </div>

            <div class="col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12 ">
                <p class="h6">Получатель: ________________</p>
                <p class="h6">Основание: Заявка 00001 г.</p>
                <p class="h6">Через: ID 001</p>
            </div>
            <div class="col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12 pt-3 text-center justify-content-center">
                <table class="table table-bordered">
                    <thead>

                    </thead>
                    <tbody>

                        <tr>
                            <th>{% trans "Clinet" %}</th>
                            <th>{% trans "Name" %}</th>
                            <th>{% trans "Selected" %}</th>
                            <th>{% trans "Amount" %}</th>
                            <th>{% trans "Price" %}</th>
                            <th>{% trans "Wtihout Price VAT" %}</th>
                            <th>{% trans "VAT" %}</th>
                            <th>{% trans "Price VAT" %}</th>
                            <th>{% trans "Total" %}</th>
                        </tr>
                        {% for data in datas %}

                        <tr>
                            <td class="pt-3">{{data.student.client|truncatewords:'1'}}</td>
                            <td class="pt-3">{{data.name}}</td>
                            <td class="pt-5">{{data.status_order}}</td>
                            <td class="pt-5">{{data.amount}}</td>
                            <td class="pt-5">{{data.price}}</td>
                            <td class="pt-5">{{data.without_percent_price|truncatechars:5}}</td>
                            <td class="pt-5">{{data.VAT}}</td>
                            <td class="pt-5">{{data.total_sum_wit_nds|truncatechars:5}}</td>
                            <td class="pt-5">{{data.total_sum_wit_nds|truncatechars:5}}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>

            <div class="col-12 col-sm-12 col-md-12 col-lg-6 col-xl-6">
                <h6> Разрешил _____________________</h6>
                <h6>Отпустил ______________________</h6>
            </div>
            <div class="col-12 col-sm-12 col-md-12 col-lg-6 col-xl-6">
                <h6>Гл.бухгалтер _____________________</h6>
                <h6>Получил _________________________</h6>
            </div>

        </div>
    </div>
</section>


<p><a href="{% url 'myprint:create_pdf' %}" style="

    width: 200px; 
    height: 50px; 
    background: green; 
    color: white; 
    border: none;
    border-radius: 8px;
    margin-left: 80%;  
    margin-bottom: 20px;
    padding: 10px;;

">{% trans "CONVERT PDF" %}</a></p><br>
{% endblock %}